# Generated by Django 5.1.5 on 2025-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gamehistory_game_alter_gamehistory_move_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='move',
            field=models.CharField(max_length=2),
        ),
    ]
